import { useTranslation } from '../i18n/useTranslation';
import { LegalPageLayout } from './LegalPageLayout';

const content = {
  uk: {
    title: "Політика Cookie",
    updated: "Останнє оновлення: червень 2026",
    h1: "Що таке cookie?",
    p1: "Cookie (файли cookie) — це невеликі текстові файли, які зберігаються у вашому браузері під час відвідування веб-сайтів. Вони допомагають сайту запам'ятовувати ваші налаштування та покращувати досвід використання.",
    h2: "Які cookie ми використовуємо",
    h3_1: "Технічно необхідні cookie",
    p2: "Ці cookie забезпечують базову функціональність Сервісу і не можуть бути вимкнені.",
    th1: "Cookie",
    th2: "Призначення",
    th3: "Термін дії",
    tr1_td2: "Збереження обраної мови інтерфейсу",
    tr1_td3: "1 рік",
    tr2_td2: "Збереження обраної теми (світла/темна)",
    tr2_td3: "1 рік",
    tr3_td2: "Збереження вашого вибору щодо cookie",
    tr3_td3: "1 рік",
    h3_2: "Аналітичні cookie (за вашою згодою)",
    p3: "Якщо ви надали згоду, ми можемо використовувати аналітичні cookie для розуміння того, як відвідувачі користуються Сервісом.",
    tr4_td2: "Google Analytics — анонімна статистика відвідувань",
    tr4_td3: "до 2 років",
    p4: "Аналітичні cookie встановлюються тільки після вашої явної згоди.",
    h4: "Як керувати cookie",
    p5: "Ви можете будь-коли змінити свої налаштування cookie:",
    l4_1_strong: "У Сервісі:",
    l4_1: "через банер cookie, який з'являється при першому відвідуванні.",
    l4_2_strong: "У браузері:",
    l4_2: "через налаштування браузера ви можете видалити існуючі cookie або заборонити їх встановлення. Зверніть увагу: блокування технічних cookie може вплинути на роботу Сервісу.",
    h5: "Cookie третіх сторін",
    p6: "Сервіс не використовує рекламних cookie і не передає дані рекламним мережам.",
    h6: "Контакти",
    p7: "З питань щодо cookie — зверніться через pokhyton.i@gmail.com."
  },
  en: {
    title: "Cookie Policy",
    updated: "Last updated: June 2026",
    h1: "What are cookies?",
    p1: "Cookies are small text files stored in your browser when you visit websites. They help the site remember your settings and improve the user experience.",
    h2: "What cookies we use",
    h3_1: "Strictly necessary cookies",
    p2: "These cookies ensure the basic functionality of the Service and cannot be disabled.",
    th1: "Cookie",
    th2: "Purpose",
    th3: "Lifespan",
    tr1_td2: "Saving the selected interface language",
    tr1_td3: "1 year",
    tr2_td2: "Saving the selected theme (light/dark)",
    tr2_td3: "1 year",
    tr3_td2: "Saving your cookie consent choice",
    tr3_td3: "1 year",
    h3_2: "Analytical cookies (with your consent)",
    p3: "If you have given consent, we may use analytical cookies to understand how visitors use the Service.",
    tr4_td2: "Google Analytics — anonymous visit statistics",
    tr4_td3: "up to 2 years",
    p4: "Analytical cookies are set only after your explicit consent.",
    h4: "How to manage cookies",
    p5: "You can change your cookie settings at any time:",
    l4_1_strong: "In the Service:",
    l4_1: "via the cookie banner that appears on your first visit.",
    l4_2_strong: "In your browser:",
    l4_2: "via your browser settings, you can delete existing cookies or prevent them from being set. Please note: blocking technical cookies may affect the operation of the Service.",
    h5: "Third-party cookies",
    p6: "The Service does not use advertising cookies and does not transmit data to advertising networks.",
    h6: "Contacts",
    p7: "For questions about cookies — contact pokhyton.i@gmail.com."
  },
  pl: {
    title: "Polityka Cookie",
    updated: "Ostatnia aktualizacja: Czerwiec 2026",
    h1: "Czym są pliki cookie?",
    p1: "Pliki cookie to małe pliki tekstowe przechowywane w przeglądarce podczas odwiedzania stron internetowych. Pomagają one witrynie zapamiętać Twoje ustawienia i poprawić wrażenia z użytkowania.",
    h2: "Jakich plików cookie używamy",
    h3_1: "Niezbędne pliki cookie",
    p2: "Te pliki cookie zapewniają podstawową funkcjonalność Serwisu i nie mogą być wyłączone.",
    th1: "Cookie",
    th2: "Cel",
    th3: "Czas trwania",
    tr1_td2: "Zapisywanie wybranego języka interfejsu",
    tr1_td3: "1 rok",
    tr2_td2: "Zapisywanie wybranego motywu (jasny/ciemny)",
    tr2_td3: "1 rok",
    tr3_td2: "Zapisywanie Twojego wyboru zgody na cookie",
    tr3_td3: "1 rok",
    h3_2: "Analityczne pliki cookie (za Twoją zgodą)",
    p3: "Jeśli wyraziłeś zgodę, możemy używać analitycznych plików cookie, aby zrozumieć, jak odwiedzający korzystają z Serwisu.",
    tr4_td2: "Google Analytics — anonimowe statystyki odwiedzin",
    tr4_td3: "do 2 lat",
    p4: "Analityczne pliki cookie są instalowane tylko po uzyskaniu wyraźnej zgody użytkownika.",
    h4: "Jak zarządzać plikami cookie",
    p5: "W każdej chwili możesz zmienić ustawienia plików cookie:",
    l4_1_strong: "W Serwisie:",
    l4_1: "poprzez baner cookie, który pojawia się podczas pierwszej wizyty.",
    l4_2_strong: "W przeglądarce:",
    l4_2: "w ustawieniach przeglądarki możesz usunąć istniejące pliki cookie lub zapobiec ich instalacji. Uwaga: blokowanie technicznych plików cookie może wpłynąć na działanie Serwisu.",
    h5: "Pliki cookie stron trzecich",
    p6: "Serwis nie używa reklamowych plików cookie i nie przekazuje danych do sieci reklamowych.",
    h6: "Kontakty",
    p7: "W przypadku pytań dotyczących plików cookie — skontaktuj się pod adresem pokhyton.i@gmail.com."
  },
  de: {
    title: "Cookie-Richtlinie",
    updated: "Zuletzt aktualisiert: Juni 2026",
    h1: "Was sind Cookies?",
    p1: "Cookies sind kleine Textdateien, die in Ihrem Browser gespeichert werden, wenn Sie Websites besuchen. Sie helfen der Website, sich an Ihre Einstellungen zu erinnern und die Benutzererfahrung zu verbessern.",
    h2: "Welche Cookies wir verwenden",
    h3_1: "Unbedingt erforderliche Cookies",
    p2: "Diese Cookies gewährleisten die grundlegende Funktionalität des Dienstes und können nicht deaktiviert werden.",
    th1: "Cookie",
    th2: "Zweck",
    th3: "Lebensdauer",
    tr1_td2: "Speichern der ausgewählten Schnittstellensprache",
    tr1_td3: "1 Jahr",
    tr2_td2: "Speichern des ausgewählten Designs (hell/dunkel)",
    tr2_td3: "1 Jahr",
    tr3_td2: "Speichern Ihrer Cookie-Zustimmung",
    tr3_td3: "1 Jahr",
    h3_2: "Analytische Cookies (mit Ihrer Zustimmung)",
    p3: "Wenn Sie zugestimmt haben, können wir analytische Cookies verwenden, um zu verstehen, wie Besucher den Dienst nutzen.",
    tr4_td2: "Google Analytics — anonyme Besuchsstatistiken",
    tr4_td3: "bis zu 2 Jahre",
    p4: "Analytische Cookies werden nur nach Ihrer ausdrücklichen Zustimmung gesetzt.",
    h4: "Wie man Cookies verwaltet",
    p5: "Sie können Ihre Cookie-Einstellungen jederzeit ändern:",
    l4_1_strong: "Im Dienst:",
    l4_1: "über das Cookie-Banner, das bei Ihrem ersten Besuch angezeigt wird.",
    l4_2_strong: "In Ihrem Browser:",
    l4_2: "über Ihre Browsereinstellungen können Sie vorhandene Cookies löschen oder deren Setzen verhindern. Bitte beachten Sie: Das Blockieren technischer Cookies kann den Betrieb des Dienstes beeinträchtigen.",
    h5: "Cookies von Drittanbietern",
    p6: "Der Dienst verwendet keine Werbe-Cookies und überträgt keine Daten an Werbenetzwerke.",
    h6: "Kontakte",
    p7: "Bei Fragen zu Cookies — kontaktieren Sie pokhyton.i@gmail.com."
  },
  fr: {
    title: "Politique relative aux cookies",
    updated: "Dernière mise à jour : Juin 2026",
    h1: "Que sont les cookies ?",
    p1: "Les cookies sont de petits fichiers texte stockés dans votre navigateur lorsque vous visitez des sites Web. Ils aident le site à mémoriser vos paramètres et à améliorer l'expérience utilisateur.",
    h2: "Quels cookies nous utilisons",
    h3_1: "Cookies strictement nécessaires",
    p2: "Ces cookies assurent la fonctionnalité de base du Service et ne peuvent pas être désactivés.",
    th1: "Cookie",
    th2: "Objectif",
    th3: "Durée de vie",
    tr1_td2: "Enregistrement de la langue d'interface sélectionnée",
    tr1_td3: "1 an",
    tr2_td2: "Enregistrement du thème sélectionné (clair/sombre)",
    tr2_td3: "1 an",
    tr3_td2: "Enregistrement de votre choix de consentement aux cookies",
    tr3_td3: "1 an",
    h3_2: "Cookies analytiques (avec votre consentement)",
    p3: "Si vous y avez consenti, nous pouvons utiliser des cookies analytiques pour comprendre comment les visiteurs utilisent le Service.",
    tr4_td2: "Google Analytics — statistiques de visites anonymes",
    tr4_td3: "jusqu'à 2 ans",
    p4: "Les cookies analytiques ne sont définis qu'après votre consentement explicite.",
    h4: "Comment gérer les cookies",
    p5: "Vous pouvez modifier vos paramètres de cookies à tout moment :",
    l4_1_strong: "Dans le Service :",
    l4_1: "via la bannière de cookies qui apparaît lors de votre première visite.",
    l4_2_strong: "Dans votre navigateur :",
    l4_2: "via les paramètres de votre navigateur, vous pouvez supprimer les cookies existants ou empêcher leur configuration. Veuillez noter : le blocage des cookies techniques peut affecter le fonctionnement du Service.",
    h5: "Cookies tiers",
    p6: "Le Service n'utilise pas de cookies publicitaires et ne transmet pas de données aux réseaux publicitaires.",
    h6: "Contacts",
    p7: "Pour des questions concernant les cookies — contactez pokhyton.i@gmail.com."
  },
  es: {
    title: "Política de Cookies",
    updated: "Última actualización: Junio de 2026",
    h1: "¿Qué son las cookies?",
    p1: "Las cookies son pequeños archivos de texto almacenados en su navegador cuando visita sitios web. Ayudan al sitio a recordar sus configuraciones y mejorar la experiencia del usuario.",
    h2: "Qué cookies usamos",
    h3_1: "Cookies estrictamente necesarias",
    p2: "Estas cookies garantizan la funcionalidad básica del Servicio y no se pueden desactivar.",
    th1: "Cookie",
    th2: "Propósito",
    th3: "Vida útil",
    tr1_td2: "Guardar el idioma de la interfaz seleccionado",
    tr1_td3: "1 año",
    tr2_td2: "Guardar el tema seleccionado (claro/oscuro)",
    tr2_td3: "1 año",
    tr3_td2: "Guardar su elección de consentimiento de cookies",
    tr3_td3: "1 año",
    h3_2: "Cookies analíticas (con su consentimiento)",
    p3: "Si ha dado su consentimiento, podemos usar cookies analíticas para comprender cómo los visitantes interactúan con el Servicio.",
    tr4_td2: "Google Analytics — estadísticas de visitas anónimas",
    tr4_td3: "hasta 2 años",
    p4: "Las cookies analíticas solo se establecen después de su consentimiento explícito.",
    h4: "Cómo gestionar las cookies",
    p5: "Puede cambiar su configuración de cookies en cualquier momento:",
    l4_1_strong: "En el Servicio:",
    l4_1: "a través del banner de cookies que aparece en su primera visita.",
    l4_2_strong: "En su navegador:",
    l4_2: "a través de la configuración de su navegador, puede eliminar las cookies existentes o evitar que se establezcan. Tenga en cuenta: el bloqueo de cookies técnicas puede afectar el funcionamiento del Servicio.",
    h5: "Cookies de terceros",
    p6: "El Servicio no utiliza cookies publicitarias y no transmite datos a redes publicitarias.",
    h6: "Contactos",
    p7: "Para preguntas sobre las cookies — contacte a pokhyton.i@gmail.com."
  },
  it: {
    title: "Informativa sui cookie",
    updated: "Ultimo aggiornamento: Giugno 2026",
    h1: "Cosa sono i cookie?",
    p1: "I cookie sono piccoli file di testo memorizzati nel tuo browser quando visiti i siti web. Aiutano il sito a ricordare le tue impostazioni e a migliorare l'esperienza utente.",
    h2: "Quali cookie utilizziamo",
    h3_1: "Cookie strettamente necessari",
    p2: "Questi cookie garantiscono le funzionalità di base del Servizio e non possono essere disabilitati.",
    th1: "Cookie",
    th2: "Scopo",
    th3: "Durata",
    tr1_td2: "Salvataggio della lingua dell'interfaccia selezionata",
    tr1_td3: "1 anno",
    tr2_td2: "Salvataggio del tema selezionato (chiaro/scuro)",
    tr2_td3: "1 anno",
    tr3_td2: "Salvataggio della scelta di consenso ai cookie",
    tr3_td3: "1 anno",
    h3_2: "Cookie analitici (con il tuo consenso)",
    p3: "Se hai prestato il consenso, potremmo utilizzare cookie analitici per capire come i visitatori utilizzano il Servizio.",
    tr4_td2: "Google Analytics — statistiche di visite anonime",
    tr4_td3: "fino a 2 anni",
    p4: "I cookie analitici vengono impostati solo dopo il tuo esplicito consenso.",
    h4: "Come gestire i cookie",
    p5: "Puoi modificare le impostazioni dei cookie in qualsiasi momento:",
    l4_1_strong: "Nel Servizio:",
    l4_1: "tramite il banner dei cookie che appare alla tua prima visita.",
    l4_2_strong: "Nel tuo browser:",
    l4_2: "tramite le impostazioni del tuo browser, puoi eliminare i cookie esistenti o impedirne l'impostazione. Nota bene: il blocco dei cookie tecnici potrebbe influire sul funzionamento del Servizio.",
    h5: "Cookie di terze parti",
    p6: "Il Servizio non utilizza cookie pubblicitari e non trasmette dati a reti pubblicitarie.",
    h6: "Contatti",
    p7: "Per domande sui cookie — contatta pokhyton.i@gmail.com."
  },
  pt: {
    title: "Política de Cookies",
    updated: "Última atualização: Junho de 2026",
    h1: "O que são cookies?",
    p1: "Cookies são pequenos arquivos de texto armazenados em seu navegador quando você visita sites. Eles ajudam o site a lembrar de suas configurações e a melhorar a experiência do usuário.",
    h2: "Quais cookies usamos",
    h3_1: "Cookies estritamente necessários",
    p2: "Esses cookies garantem a funcionalidade básica do Serviço e não podem ser desativados.",
    th1: "Cookie",
    th2: "Finalidade",
    th3: "Duração",
    tr1_td2: "Salvar o idioma da interface selecionado",
    tr1_td3: "1 ano",
    tr2_td2: "Salvar o tema selecionado (claro/escuro)",
    tr2_td3: "1 ano",
    tr3_td2: "Salvar a sua escolha de consentimento de cookies",
    tr3_td3: "1 ano",
    h3_2: "Cookies analíticos (com o seu consentimento)",
    p3: "Se você deu o seu consentimento, podemos usar cookies analíticos para entender como os visitantes usam o Serviço.",
    tr4_td2: "Google Analytics — estatísticas de visitas anônimas",
    tr4_td3: "até 2 anos",
    p4: "Os cookies analíticos são definidos apenas após o seu consentimento explícito.",
    h4: "Como gerenciar cookies",
    p5: "Você pode alterar suas configurações de cookies a qualquer momento:",
    l4_1_strong: "No Serviço:",
    l4_1: "através do banner de cookies que aparece na sua primeira visita.",
    l4_2_strong: "No seu navegador:",
    l4_2: "através das configurações do seu navegador, você pode excluir os cookies existentes ou impedir que sejam definidos. Observação: o bloqueio de cookies técnicos pode afetar o funcionamento do Serviço.",
    h5: "Cookies de terceiros",
    p6: "O Serviço não usa cookies de publicidade e não transmite dados para redes de publicidade.",
    h6: "Contatos",
    p7: "Para dúvidas sobre cookies — contate pokhyton.i@gmail.com."
  },
  tr: {
    title: "Çerez Politikası",
    updated: "Son güncelleme: Haziran 2026",
    h1: "Çerezler nedir?",
    p1: "Çerezler, web sitelerini ziyaret ettiğinizde tarayıcınızda saklanan küçük metin dosyalarıdır. Sitenin ayarlarınızı hatırlamasına ve kullanıcı deneyimini iyileştirmesine yardımcı olurlar.",
    h2: "Hangi çerezleri kullanıyoruz",
    h3_1: "Kesinlikle gerekli çerezler",
    p2: "Bu çerezler Hizmetin temel işlevselliğini sağlar ve devre dışı bırakılamaz.",
    th1: "Çerez",
    th2: "Amaç",
    th3: "Ömür",
    tr1_td2: "Seçilen arayüz dilini kaydetme",
    tr1_td3: "1 yıl",
    tr2_td2: "Seçilen temayı kaydetme (açık/koyu)",
    tr2_td3: "1 yıl",
    tr3_td2: "Çerez onayı seçiminizi kaydetme",
    tr3_td3: "1 yıl",
    h3_2: "Analitik çerezler (izninizle)",
    p3: "Onay verdiyseniz, ziyaretçilerin Hizmeti nasıl kullandığını anlamak için analitik çerezler kullanabiliriz.",
    tr4_td2: "Google Analytics — anonim ziyaret istatistikleri",
    tr4_td3: "2 yıla kadar",
    p4: "Analitik çerezler yalnızca açık onayınızın ardından ayarlanır.",
    h4: "Çerezler nasıl yönetilir",
    p5: "Çerez ayarlarınızı istediğiniz zaman değiştirebilirsiniz:",
    l4_1_strong: "Hizmette:",
    l4_1: "ilk ziyaretinizde görünen çerez başlığı aracılığıyla.",
    l4_2_strong: "Tarayıcınızda:",
    l4_2: "tarayıcı ayarlarınız aracılığıyla mevcut çerezleri silebilir veya ayarlanmalarını engelleyebilirsiniz. Lütfen dikkat: teknik çerezlerin engellenmesi Hizmetin çalışmasını etkileyebilir.",
    h5: "Üçüncü taraf çerezleri",
    p6: "Hizmet reklam çerezleri kullanmaz ve reklam ağlarına veri iletmez.",
    h6: "İletişim",
    p7: "Çerezlerle ilgili sorularınız için — pokhyton.i@gmail.com adresinden iletişime geçin."
  },
  zh: {
    title: "Cookie政策",
    updated: "最后更新：2026年6月",
    h1: "什么是cookies？",
    p1: "Cookies是您访问网站时存储在浏览器中的小型文本文件。它们帮助网站记住您的设置并改善用户体验。",
    h2: "我们使用哪些cookie",
    h3_1: "绝对必要的cookies",
    p2: "这些cookie确保服务的基本功能，不能被禁用。",
    th1: "Cookie",
    th2: "用途",
    th3: "生命周期",
    tr1_td2: "保存所选的界面语言",
    tr1_td3: "1年",
    tr2_td2: "保存所选的主题（浅色/深色）",
    tr2_td3: "1年",
    tr3_td2: "保存您的cookie同意选择",
    tr3_td3: "1年",
    h3_2: "分析cookies（需您同意）",
    p3: "如果您已同意，我们可能会使用分析cookie来了解访问者如何使用该服务。",
    tr4_td2: "Google Analytics — 匿名访问统计",
    tr4_td3: "最多2年",
    p4: "分析cookie仅在您明确同意后才会设置。",
    h4: "如何管理cookies",
    p5: "您可以随时更改您的cookie设置：",
    l4_1_strong: "在服务中：",
    l4_1: "通过首次访问时出现的cookie横幅。",
    l4_2_strong: "在您的浏览器中：",
    l4_2: "通过您的浏览器设置，您可以删除现有的cookie或阻止设置它们。请注意：阻止技术cookie可能会影响服务的运行。",
    h5: "第三方cookies",
    p6: "该服务不使用广告cookie，也不会向广告网络传输数据。",
    h6: "联系方式",
    p7: "有关cookie的问题 — 请联系pokhyton.i@gmail.com。"
  },
  ja: {
    title: "Cookieポリシー",
    updated: "最終更新日：2026年6月",
    h1: "Cookieとは？",
    p1: "Cookieは、Webサイトにアクセスしたときにブラウザに保存される小さなテキストファイルです。サイトが設定を記憶し、ユーザーエクスペリエンスを向上させるのに役立ちます。",
    h2: "使用するCookie",
    h3_1: "厳密に必要なCookie",
    p2: "これらのCookieはサービスの基本機能を確保し、無効にすることはできません。",
    th1: "Cookie",
    th2: "目的",
    th3: "寿命",
    tr1_td2: "選択したインターフェース言語を保存",
    tr1_td3: "1年",
    tr2_td2: "選択したテーマ（ライト/ダーク）を保存",
    tr2_td3: "1年",
    tr3_td2: "Cookieへの同意の選択を保存",
    tr3_td3: "1年",
    h3_2: "分析Cookie（同意がある場合）",
    p3: "同意が得られた場合、訪問者がサービスをどのように使用しているかを理解するために分析Cookieを使用する場合があります。",
    tr4_td2: "Google Analytics — 匿名の訪問統計",
    tr4_td3: "最大2年",
    p4: "分析Cookieは、明示的な同意があった後にのみ設定されます。",
    h4: "Cookieの管理方法",
    p5: "Cookieの設定はいつでも変更できます：",
    l4_1_strong: "サービス内：",
    l4_1: "最初の訪問時に表示されるCookieバナーから。",
    l4_2_strong: "ブラウザ内：",
    l4_2: "ブラウザの設定を通じて、既存のCookieを削除したり、Cookieが設定されないようにすることができます。注意：技術的なCookieをブロックすると、サービスの運用に影響を与える可能性があります。",
    h5: "サードパーティCookie",
    p6: "サービスは広告Cookieを使用せず、広告ネットワークにデータを送信しません。",
    h6: "連絡先",
    p7: "Cookieに関する質問 — pokhyton.i@gmail.comまでご連絡ください。"
  },
  ko: {
    title: "쿠키 정책",
    updated: "최근 업데이트: 2026년 6월",
    h1: "쿠키란 무엇인가요?",
    p1: "쿠키는 웹사이트를 방문할 때 브라우저에 저장되는 작은 텍스트 파일입니다. 사이트에서 설정을 기억하고 사용자 경험을 개선하는 데 도움이 됩니다.",
    h2: "사용하는 쿠키",
    h3_1: "필수 쿠키",
    p2: "이 쿠키는 서비스의 기본 기능을 보장하며 비활성화할 수 없습니다.",
    th1: "쿠키",
    th2: "목적",
    th3: "수명",
    tr1_td2: "선택한 인터페이스 언어 저장",
    tr1_td3: "1년",
    tr2_td2: "선택한 테마(라이트/다크) 저장",
    tr2_td3: "1년",
    tr3_td2: "쿠키 동의 선택 저장",
    tr3_td3: "1년",
    h3_2: "분석 쿠키(동의 시)",
    p3: "귀하가 동의한 경우, 분석 쿠키를 사용하여 방문자가 서비스를 사용하는 방식을 이해할 수 있습니다.",
    tr4_td2: "Google Analytics — 익명 방문 통계",
    tr4_td3: "최대 2년",
    p4: "분석 쿠키는 명시적인 동의가 있은 후에만 설정됩니다.",
    h4: "쿠키 관리 방법",
    p5: "언제든지 쿠키 설정을 변경할 수 있습니다:",
    l4_1_strong: "서비스 내:",
    l4_1: "첫 방문 시 나타나는 쿠키 배너를 통해.",
    l4_2_strong: "브라우저 내:",
    l4_2: "브라우저 설정을 통해 기존 쿠키를 삭제하거나 설정되지 않도록 방지할 수 있습니다. 참고: 기술 쿠키를 차단하면 서비스 작동에 영향을 미칠 수 있습니다.",
    h5: "타사 쿠키",
    p6: "서비스는 광고 쿠키를 사용하지 않으며 광고 네트워크로 데이터를 전송하지 않습니다.",
    h6: "연락처",
    p7: "쿠키 관련 질문 — pokhyton.i@gmail.com으로 문의하십시오."
  },
  hi: {
    title: "कुकी नीति",
    updated: "अंतिम अद्यतन: जून 2026",
    h1: "कुकीज़ क्या हैं?",
    p1: "कुकीज़ छोटे टेक्स्ट फ़ाइलें हैं जो वेबसाइट पर जाने पर आपके ब्राउज़र में संग्रहीत की जाती हैं। वे साइट को आपकी सेटिंग्स को याद रखने और उपयोगकर्ता अनुभव को बेहतर बनाने में मदद करते हैं।",
    h2: "हम किन कुकीज़ का उपयोग करते हैं",
    h3_1: "कड़ाई से आवश्यक कुकीज़",
    p2: "ये कुकीज़ सेवा की बुनियादी कार्यक्षमता सुनिश्चित करती हैं और इन्हें अक्षम नहीं किया जा सकता है।",
    th1: "कुकी",
    th2: "उद्देश्य",
    th3: "जीवन काल",
    tr1_td2: "चयनित इंटरफ़ेस भाषा को सहेजना",
    tr1_td3: "1 वर्ष",
    tr2_td2: "चयनित थीम को सहेजना (प्रकाश/अंधकार)",
    tr2_td3: "1 वर्ष",
    tr3_td2: "अपनी कुकी सहमति विकल्प को सहेजना",
    tr3_td3: "1 वर्ष",
    h3_2: "विश्लेषणात्मक कुकीज़ (आपकी सहमति से)",
    p3: "यदि आपने सहमति दी है, तो हम यह समझने के लिए विश्लेषणात्मक कुकीज़ का उपयोग कर सकते हैं कि विज़िटर सेवा का उपयोग कैसे करते हैं।",
    tr4_td2: "Google Analytics — अनाम विज़िट आँकड़े",
    tr4_td3: "2 वर्ष तक",
    p4: "विश्लेषणात्मक कुकीज़ केवल आपकी स्पष्ट सहमति के बाद ही सेट की जाती हैं।",
    h4: "कुकीज़ का प्रबंधन कैसे करें",
    p5: "आप किसी भी समय अपनी कुकी सेटिंग्स बदल सकते हैं:",
    l4_1_strong: "सेवा में:",
    l4_1: "आपकी पहली विज़िट पर दिखाई देने वाले कुकी बैनर के माध्यम से।",
    l4_2_strong: "आपके ब्राउज़र में:",
    l4_2: "अपनी ब्राउज़र सेटिंग्स के माध्यम से, आप मौजूदा कुकीज़ हटा सकते हैं या उन्हें सेट होने से रोक सकते हैं। कृपया ध्यान दें: तकनीकी कुकीज़ को ब्लॉक करने से सेवा का संचालन प्रभावित हो सकता है।",
    h5: "तृतीय-पक्ष कुकीज़",
    p6: "सेवा विज्ञापन कुकीज़ का उपयोग नहीं करती है और विज्ञापन नेटवर्क को डेटा प्रसारित नहीं करती है।",
    h6: "संपर्क",
    p7: "कुकीज़ के बारे में प्रश्नों के लिए — pokhyton.i@gmail.com पर संपर्क करें।"
  },
  ar: {
    title: "سياسة ملفات تعريف الارتباط",
    updated: "آخر تحديث: يونيو 2026",
    h1: "ما هي ملفات تعريف الارتباط؟",
    p1: "ملفات تعريف الارتباط هي ملفات نصية صغيرة يتم تخزينها في متصفحك عند زيارة مواقع الويب. تساعد الموقع على تذكر إعداداتك وتحسين تجربة المستخدم.",
    h2: "ما ملفات تعريف الارتباط التي نستخدمها",
    h3_1: "ملفات تعريف الارتباط الضرورية للغاية",
    p2: "تضمن هذه الملفات الوظائف الأساسية للخدمة ولا يمكن تعطيلها.",
    th1: "ملف تعريف الارتباط",
    th2: "الغرض",
    th3: "المدة",
    tr1_td2: "حفظ لغة الواجهة المحددة",
    tr1_td3: "سنة واحدة",
    tr2_td2: "حفظ السمة المحددة (فاتح/داكن)",
    tr2_td3: "سنة واحدة",
    tr3_td2: "حفظ اختيار موافقتك على ملفات تعريف الارتباط",
    tr3_td3: "سنة واحدة",
    h3_2: "ملفات تعريف الارتباط التحليلية (بموافقتك)",
    p3: "إذا أعطيت موافقتك، فقد نستخدم ملفات تعريف الارتباط التحليلية لفهم كيفية استخدام الزوار للخدمة.",
    tr4_td2: "Google Analytics — إحصائيات زيارة مجهولة",
    tr4_td3: "حتى سنتين",
    p4: "يتم تعيين ملفات تعريف الارتباط التحليلية فقط بعد موافقتك الصريحة.",
    h4: "كيفية إدارة ملفات تعريف الارتباط",
    p5: "يمكنك تغيير إعدادات ملفات تعريف الارتباط الخاصة بك في أي وقت:",
    l4_1_strong: "في الخدمة:",
    l4_1: "عبر لافتة ملفات تعريف الارتباط التي تظهر في زيارتك الأولى.",
    l4_2_strong: "في متصفحك:",
    l4_2: "من خلال إعدادات المتصفح، يمكنك حذف ملفات تعريف الارتباط الحالية أو منع تعيينها. يرجى ملاحظة: قد يؤدي حظر ملفات تعريف الارتباط الفنية إلى التأثير على عمل الخدمة.",
    h5: "ملفات تعريف ارتباط الطرف الثالث",
    p6: "لا تستخدم الخدمة ملفات تعريف ارتباط إعلانية ولا تنقل البيانات إلى شبكات الإعلان.",
    h6: "جهات الاتصال",
    p7: "للأسئلة المتعلقة بملفات تعريف الارتباط — اتصل بـ pokhyton.i@gmail.com."
  }
};

export const CookiesPage = () => {
  const { locale: lang } = useTranslation();

  const t = (content as any)[lang] || content.en;
  
  return (
    <LegalPageLayout>
      <div dir={lang === 'ar' ? 'rtl' : 'ltr'}>
        <h1>{t.title}</h1>
        <p className="last-updated">{t.updated}</p>

        <h2>{t.h1}</h2>
        <p>{t.p1}</p>

        <h2>{t.h2}</h2>

        <h3>{t.h3_1}</h3>
        <p>{t.p2}</p>
        <table>
          <thead>
            <tr>
              <th>{t.th1}</th>
              <th>{t.th2}</th>
              <th>{t.th3}</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><code>locale</code></td>
              <td>{t.tr1_td2}</td>
              <td>{t.tr1_td3}</td>
            </tr>
            <tr>
              <td><code>theme</code></td>
              <td>{t.tr2_td2}</td>
              <td>{t.tr2_td3}</td>
            </tr>
            
          </tbody>
        </table>

        

        <h2>{t.h4}</h2>
        <p>{t.p5}</p>
        <ul>
          <li><strong>{t.l4_2_strong}</strong> {t.l4_2}</li>
        </ul>

        <h2>{t.h5}</h2>
        <p>{t.p6}</p>

        <h2>{t.h6}</h2>
        <p>{t.p7}</p>
      </div>
    </LegalPageLayout>
  );
};
