import { useTranslation } from '../i18n/useTranslation';
import { LegalPageLayout } from './LegalPageLayout';

interface Props {
  
}

const content = {
  uk: {
    title: "Умови використання",
    updated: "Останнє оновлення: червень 2026",
    h1: "1. Предмет",
    p1: "Ці Умови використання (далі — Умови) регулюють відносини між вами (далі — Користувач) та Redempsly (далі — Розробник) щодо використання веб-додатку «Складний відсоток» (далі — Сервіс).",
    p2: "Використовуючи Сервіс, ви підтверджуєте, що ознайомилися з цими Умовами та погоджуєтесь з ними.",
    h2: "2. Опис Сервісу",
    p3: "Сервіс — це безкоштовний онлайн-калькулятор складного відсотка, який дозволяє моделювати зростання інвестицій з урахуванням регулярних поповнень, інфляції, податків та різних ставок дохідності.",
    h3: "3. Обмеження відповідальності",
    p4_strong: "Сервіс має виключно інформаційний та освітній характер.",
    l3_1: "Результати розрахунків є приблизними і мають ілюстративний характер.",
    l3_2: "Сервіс не є фінансовою, інвестиційною, податковою чи юридичною порадою.",
    l3_3: "Розробник не несе відповідальності за будь-які фінансові рішення, прийняті на основі результатів калькулятора.",
    l3_4: "Реальні показники можуть відрізнятися через зміну відсоткових ставок, рівня інфляції, податкового законодавства, комісій та інших ринкових факторів.",
    l3_5: "Минулі результати не гарантують майбутніх.",
    p5: "Перед прийняттям інвестиційних рішень рекомендуємо звернутися до кваліфікованого фінансового радника.",
    h4: "4. Інтелектуальна власність",
    p6: "Весь контент Сервісу, включаючи дизайн, код, тексти, графіку та логотипи, є інтелектуальною власністю Розробника або використовується на підставі відповідних ліцензій. Забороняється копіювання, модифікація або розповсюдження будь-яких елементів Сервісу без попередньої письмової згоди Розробника.",
    h5: "5. Доступність Сервісу",
    p7: "Розробник докладає зусиль для забезпечення безперебійної роботи Сервісу, але не гарантує його постійну доступність. Сервіс може бути тимчасово недоступний через технічне обслуговування, оновлення або обставини непереборної сили.",
    h6: "6. Заборонене використання",
    p8: "Користувачу забороняється:",
    l6_1: "використовувати Сервіс для незаконних цілей;",
    l6_2: "намагатися отримати несанкціонований доступ до Сервісу або його інфраструктури;",
    l6_3: "використовувати автоматизовані засоби (боти, скрапери) для масового доступу до Сервісу;",
    l6_4: "видавати результати Сервісу за професійну фінансову пораду.",
    h7: "7. Зміни до Умов",
    p9: "Розробник залишає за собою право змінювати ці Умови. Продовження використання Сервісу після внесення змін означає вашу згоду з оновленими Умовами.",
    h8: "8. Застосовне право",
    p10: "Ці Умови регулюються чинним законодавством України. Будь-які спори, що виникають у зв'язку з використанням Сервісу, вирішуються шляхом переговорів, а в разі недосягнення згоди — у відповідному суді за місцем знаходження Розробника.",
    h9: "9. Контакти",
    p11: "З питань щодо цих Умов — зверніться через pokhyton.i@gmail.com."
  },
  en: {
    title: "Terms of Use",
    updated: "Last updated: June 2026",
    h1: "1. Subject Matter",
    p1: "These Terms of Use (hereinafter - Terms) govern the relationship between you (hereinafter - User) and Redempsly (hereinafter - Developer) regarding the use of the \"Compound Interest\" web application (hereinafter - Service).",
    p2: "By using the Service, you confirm that you have read these Terms and agree to them.",
    h2: "2. Service Description",
    p3: "The Service is a free online compound interest calculator that allows modeling investment growth taking into account regular contributions, inflation, taxes, and various rates of return.",
    h3: "3. Limitation of Liability",
    p4_strong: "The Service is for informational and educational purposes only.",
    l3_1: "Calculation results are approximate and illustrative.",
    l3_2: "The Service is not financial, investment, tax, or legal advice.",
    l3_3: "The Developer is not responsible for any financial decisions made based on the calculator's results.",
    l3_4: "Real figures may differ due to changes in interest rates, inflation levels, tax laws, fees, and other market factors.",
    l3_5: "Past performance does not guarantee future results.",
    p5: "Before making investment decisions, we recommend consulting a qualified financial advisor.",
    h4: "4. Intellectual Property",
    p6: "All Service content, including design, code, texts, graphics, and logos, is the intellectual property of the Developer or is used under appropriate licenses. Copying, modifying, or distributing any elements of the Service without prior written consent from the Developer is prohibited.",
    h5: "5. Service Availability",
    p7: "The Developer makes efforts to ensure uninterrupted operation of the Service, but does not guarantee its continuous availability. The Service may be temporarily unavailable due to maintenance, updates, or force majeure circumstances.",
    h6: "6. Prohibited Use",
    p8: "The User is prohibited from:",
    l6_1: "using the Service for illegal purposes;",
    l6_2: "attempting to gain unauthorized access to the Service or its infrastructure;",
    l6_3: "using automated means (bots, scrapers) for mass access to the Service;",
    l6_4: "passing off the Service's results as professional financial advice.",
    h7: "7. Changes to Terms",
    p9: "The Developer reserves the right to change these Terms. Continued use of the Service after changes are made means your agreement to the updated Terms.",
    h8: "8. Applicable Law",
    p10: "These Terms are governed by the current legislation of Ukraine. Any disputes arising in connection with the use of the Service shall be resolved through negotiations, and if agreement is not reached, in the appropriate court at the Developer's location.",
    h9: "9. Contacts",
    p11: "For questions regarding these Terms, contact pokhyton.i@gmail.com."
  },
  pl: {
    title: "Regulamin",
    updated: "Ostatnia aktualizacja: Czerwiec 2026",
    h1: "1. Przedmiot",
    p1: "Niniejszy Regulamin (dalej - Regulamin) określa zasady relacji pomiędzy Tobą (dalej - Użytkownik) a firmą Redempsly (dalej - Deweloper) w zakresie korzystania z aplikacji internetowej \"Procent składany\" (dalej - Serwis).",
    p2: "Korzystając z Serwisu, potwierdzasz, że zapoznałeś się z niniejszym Regulaminem i akceptujesz go.",
    h2: "2. Opis Serwisu",
    p3: "Serwis to darmowy internetowy kalkulator procentu składanego, który pozwala na modelowanie wzrostu inwestycji z uwzględnieniem regularnych wpłat, inflacji, podatków i różnych stóp zwrotu.",
    h3: "3. Ograniczenie odpowiedzialności",
    p4_strong: "Serwis ma charakter wyłącznie informacyjny i edukacyjny.",
    l3_1: "Wyniki obliczeń są przybliżone i mają charakter poglądowy.",
    l3_2: "Serwis nie stanowi porady finansowej, inwestycyjnej, podatkowej ani prawnej.",
    l3_3: "Deweloper nie ponosi odpowiedzialności za jakiekolwiek decyzje finansowe podjęte na podstawie wyników kalkulatora.",
    l3_4: "Rzeczywiste wyniki mogą się różnić w związku ze zmianami stóp procentowych, inflacji, przepisów podatkowych, opłat i innych czynników rynkowych.",
    l3_5: "Wyniki z przeszłości nie gwarantują wyników w przyszłości.",
    p5: "Przed podjęciem decyzji inwestycyjnych zalecamy skonsultowanie się z wykwalifikowanym doradcą finansowym.",
    h4: "4. Własność intelektualna",
    p6: "Cała zawartość Serwisu, w tym projekt, kod, teksty, grafika i logotypy, stanowi własność intelektualną Dewelopera lub jest używana na podstawie odpowiednich licencji. Kopiowanie, modyfikowanie lub rozpowszechnianie jakichkolwiek elementów Serwisu bez uprzedniej pisemnej zgody Dewelopera jest zabronione.",
    h5: "5. Dostępność Serwisu",
    p7: "Deweloper dokłada starań, aby zapewnić nieprzerwane działanie Serwisu, ale nie gwarantuje jego stałej dostępności. Serwis może być tymczasowo niedostępny z powodu konserwacji, aktualizacji lub siły wyższej.",
    h6: "6. Niedozwolone użycie",
    p8: "Użytkownikowi zabrania się:",
    l6_1: "korzystania z Serwisu w celach niezgodnych z prawem;",
    l6_2: "podejmowania prób uzyskania nieautoryzowanego dostępu do Serwisu lub jego infrastruktury;",
    l6_3: "używania zautomatyzowanych narzędzi (botów, scraperów) do masowego dostępu do Serwisu;",
    l6_4: "przedstawiania wyników Serwisu jako profesjonalnej porady finansowej.",
    h7: "7. Zmiany Regulaminu",
    p9: "Deweloper zastrzega sobie prawo do zmiany niniejszego Regulaminu. Dalsze korzystanie z Serwisu po wprowadzeniu zmian oznacza akceptację zaktualizowanego Regulaminu.",
    h8: "8. Prawo właściwe",
    p10: "Niniejszy Regulamin podlega aktualnemu ustawodawstwu Ukrainy. Wszelkie spory wynikające z korzystania z Serwisu będą rozwiązywane w drodze negocjacji, a w przypadku braku porozumienia - we właściwym sądzie w miejscu siedziby Dewelopera.",
    h9: "9. Kontakty",
    p11: "W przypadku pytań dotyczących niniejszego Regulaminu, prosimy o kontakt pod adresem pokhyton.i@gmail.com."
  },
  de: {
    title: "Nutzungsbedingungen",
    updated: "Zuletzt aktualisiert: Juni 2026",
    h1: "1. Gegenstand",
    p1: "Diese Nutzungsbedingungen (im Folgenden - Bedingungen) regeln das Verhältnis zwischen Ihnen (im Folgenden - Benutzer) und Redempsly (im Folgenden - Entwickler) bezüglich der Nutzung der Webanwendung \"Zinseszins\" (im Folgenden - Dienst).",
    p2: "Durch die Nutzung des Dienstes bestätigen Sie, dass Sie diese Bedingungen gelesen haben und ihnen zustimmen.",
    h2: "2. Dienstbeschreibung",
    p3: "Der Dienst ist ein kostenloser Online-Zinseszinsrechner, der die Modellierung des Investitionswachstums unter Berücksichtigung regelmäßiger Beiträge, Inflation, Steuern und verschiedener Renditen ermöglicht.",
    h3: "3. Haftungsbeschränkung",
    p4_strong: "Der Dienst dient ausschließlich Informations- und Bildungszwecken.",
    l3_1: "Die Berechnungsergebnisse sind ungefähre Angaben und dienen zur Veranschaulichung.",
    l3_2: "Der Dienst stellt keine finanzielle, Anlage-, Steuer- oder Rechtsberatung dar.",
    l3_3: "Der Entwickler ist nicht verantwortlich für finanzielle Entscheidungen, die auf der Grundlage der Ergebnisse des Rechners getroffen werden.",
    l3_4: "Tatsächliche Zahlen können aufgrund von Änderungen der Zinssätze, des Inflationsniveaus, der Steuergesetze, Gebühren und anderer Marktfaktoren abweichen.",
    l3_5: "Die Leistung in der Vergangenheit ist keine Garantie für zukünftige Ergebnisse.",
    p5: "Bevor Sie Anlageentscheidungen treffen, empfehlen wir, einen qualifizierten Finanzberater zu konsultieren.",
    h4: "4. Geistiges Eigentum",
    p6: "Alle Inhalte des Dienstes, einschließlich Design, Code, Texte, Grafiken und Logos, sind geistiges Eigentum des Entwicklers oder werden unter entsprechenden Lizenzen verwendet. Das Kopieren, Ändern oder Verteilen von Elementen des Dienstes ohne vorherige schriftliche Zustimmung des Entwicklers ist untersagt.",
    h5: "5. Verfügbarkeit des Dienstes",
    p7: "Der Entwickler bemüht sich, einen ununterbrochenen Betrieb des Dienstes sicherzustellen, garantiert jedoch keine kontinuierliche Verfügbarkeit. Der Dienst kann aufgrund von Wartungsarbeiten, Updates oder höherer Gewalt vorübergehend nicht verfügbar sein.",
    h6: "6. Verbotene Nutzung",
    p8: "Dem Benutzer ist Folgendes untersagt:",
    l6_1: "Nutzung des Dienstes für illegale Zwecke;",
    l6_2: "Versuch, sich unbefugten Zugriff auf den Dienst oder seine Infrastruktur zu verschaffen;",
    l6_3: "Verwendung automatisierter Mittel (Bots, Scraper) für den Massenzugriff auf den Dienst;",
    l6_4: "Weitergabe der Ergebnisse des Dienstes als professionelle Finanzberatung.",
    h7: "7. Änderungen der Bedingungen",
    p9: "Der Entwickler behält sich das Recht vor, diese Bedingungen zu ändern. Die fortgesetzte Nutzung des Dienstes nach Änderungen bedeutet Ihre Zustimmung zu den aktualisierten Bedingungen.",
    h8: "8. Anwendbares Recht",
    p10: "Diese Bedingungen unterliegen der geltenden Gesetzgebung der Ukraine. Streitigkeiten im Zusammenhang mit der Nutzung des Dienstes werden durch Verhandlungen und, falls keine Einigung erzielt wird, vor dem zuständigen Gericht am Standort des Entwicklers beigelegt.",
    h9: "9. Kontakte",
    p11: "Bei Fragen zu diesen Bedingungen wenden Sie sich an pokhyton.i@gmail.com."
  },
  fr: {
    title: "Conditions d'utilisation",
    updated: "Dernière mise à jour : Juin 2026",
    h1: "1. Objet",
    p1: "Ces Conditions d'utilisation (ci-après - Conditions) régissent la relation entre vous (ci-après - Utilisateur) et Redempsly (ci-après - Développeur) concernant l'utilisation de l'application Web « Intérêts composés » (ci-après - Service).",
    p2: "En utilisant le Service, vous confirmez que vous avez lu ces Conditions et que vous les acceptez.",
    h2: "2. Description du Service",
    p3: "Le Service est un calculateur d'intérêts composés en ligne gratuit qui permet de modéliser la croissance des investissements en tenant compte des contributions régulières, de l'inflation, des impôts et de divers taux de rendement.",
    h3: "3. Limitation de responsabilité",
    p4_strong: "Le Service est à des fins d'information et d'éducation uniquement.",
    l3_1: "Les résultats de calcul sont approximatifs et illustratifs.",
    l3_2: "Le Service ne constitue pas un conseil financier, d'investissement, fiscal ou juridique.",
    l3_3: "Le Développeur n'est pas responsable des décisions financières prises sur la base des résultats du calculateur.",
    l3_4: "Les chiffres réels peuvent différer en raison de modifications des taux d'intérêt, des niveaux d'inflation, des lois fiscales, des frais et d'autres facteurs de marché.",
    l3_5: "Les performances passées ne garantissent pas les résultats futurs.",
    p5: "Avant de prendre des décisions d'investissement, nous vous recommandons de consulter un conseiller financier qualifié.",
    h4: "4. Propriété intellectuelle",
    p6: "Tout le contenu du Service, y compris la conception, le code, les textes, les graphiques et les logos, est la propriété intellectuelle du Développeur ou est utilisé sous des licences appropriées. La copie, la modification ou la distribution d'éléments du Service sans le consentement écrit préalable du Développeur est interdite.",
    h5: "5. Disponibilité du Service",
    p7: "Le Développeur s'efforce d'assurer un fonctionnement ininterrompu du Service, mais ne garantit pas sa disponibilité continue. Le Service peut être temporairement indisponible en raison de la maintenance, des mises à jour ou de circonstances de force majeure.",
    h6: "6. Utilisation interdite",
    p8: "Il est interdit à l'Utilisateur de :",
    l6_1: "utiliser le Service à des fins illégales ;",
    l6_2: "tenter d'obtenir un accès non autorisé au Service ou à son infrastructure ;",
    l6_3: "utiliser des moyens automatisés (bots, scrapers) pour un accès de masse au Service ;",
    l6_4: "faire passer les résultats du Service pour des conseils financiers professionnels.",
    h7: "7. Modifications des Conditions",
    p9: "Le Développeur se réserve le droit de modifier ces Conditions. L'utilisation continue du Service après des modifications signifie votre accord avec les Conditions mises à jour.",
    h8: "8. Droit applicable",
    p10: "Ces Conditions sont régies par la législation en vigueur en Ukraine. Tout litige survenant dans le cadre de l'utilisation du Service sera résolu par la négociation et, si aucun accord n'est trouvé, par le tribunal compétent sur le lieu de l'entreprise du Développeur.",
    h9: "9. Contacts",
    p11: "Pour des questions concernant ces Conditions, contactez pokhyton.i@gmail.com."
  },
  es: {
    title: "Términos de Uso",
    updated: "Última actualización: Junio de 2026",
    h1: "1. Objeto",
    p1: "Estos Términos de Uso (en adelante - Términos) rigen la relación entre usted (en adelante - Usuario) y Redempsly (en adelante - Desarrollador) con respecto al uso de la aplicación web \"Interés Compuesto\" (en adelante - Servicio).",
    p2: "Al utilizar el Servicio, confirma que ha leído estos Términos y los acepta.",
    h2: "2. Descripción del Servicio",
    p3: "El Servicio es una calculadora de interés compuesto en línea gratuita que permite modelar el crecimiento de las inversiones teniendo en cuenta contribuciones regulares, inflación, impuestos y diversas tasas de rendimiento.",
    h3: "3. Limitación de responsabilidad",
    p4_strong: "El Servicio es solo para fines informativos y educativos.",
    l3_1: "Los resultados de los cálculos son aproximados e ilustrativos.",
    l3_2: "El Servicio no es asesoramiento financiero, de inversión, fiscal ni legal.",
    l3_3: "El Desarrollador no es responsable de ninguna decisión financiera tomada en base a los resultados de la calculadora.",
    l3_4: "Las cifras reales pueden diferir debido a cambios en las tasas de interés, los niveles de inflación, las leyes fiscales, las tarifas y otros factores del mercado.",
    l3_5: "El rendimiento pasado no garantiza resultados futuros.",
    p5: "Antes de tomar decisiones de inversión, le recomendamos consultar a un asesor financiero calificado.",
    h4: "4. Propiedad intelectual",
    p6: "Todo el contenido del Servicio, incluido el diseño, código, textos, gráficos y logotipos, es propiedad intelectual del Desarrollador o se utiliza bajo las licencias correspondientes. Se prohíbe copiar, modificar o distribuir cualquier elemento del Servicio sin el consentimiento previo por escrito del Desarrollador.",
    h5: "5. Disponibilidad del Servicio",
    p7: "El Desarrollador hace esfuerzos para garantizar el funcionamiento ininterrumpido del Servicio, pero no garantiza su disponibilidad continua. El Servicio puede no estar disponible temporalmente debido a mantenimiento, actualizaciones o circunstancias de fuerza mayor.",
    h6: "6. Uso prohibido",
    p8: "El Usuario tiene prohibido:",
    l6_1: "usar el Servicio con fines ilegales;",
    l6_2: "intentar obtener acceso no autorizado al Servicio o a su infraestructura;",
    l6_3: "usar medios automatizados (bots, scrapers) para acceso masivo al Servicio;",
    l6_4: "hacer pasar los resultados del Servicio como asesoramiento financiero profesional.",
    h7: "7. Cambios en los Términos",
    p9: "El Desarrollador se reserva el derecho de cambiar estos Términos. El uso continuado del Servicio después de realizar cambios significa su acuerdo con los Términos actualizados.",
    h8: "8. Ley aplicable",
    p10: "Estos Términos se rigen por la legislación vigente de Ucrania. Cualquier disputa que surja en relación con el uso del Servicio se resolverá mediante negociaciones y, si no se llega a un acuerdo, en el tribunal correspondiente en la ubicación del Desarrollador.",
    h9: "9. Contactos",
    p11: "Para preguntas sobre estos Términos, comuníquese con pokhyton.i@gmail.com."
  },
  it: {
    title: "Termini di Utilizzo",
    updated: "Ultimo aggiornamento: Giugno 2026",
    h1: "1. Oggetto",
    p1: "I presenti Termini di Utilizzo (di seguito - Termini) regolano il rapporto tra te (di seguito - Utente) e Redempsly (di seguito - Sviluppatore) in merito all'utilizzo dell'applicazione web \"Interesse Composto\" (di seguito - Servizio).",
    p2: "Utilizzando il Servizio, confermi di aver letto i presenti Termini e di accettarli.",
    h2: "2. Descrizione del Servizio",
    p3: "Il Servizio è un calcolatore di interesse composto online gratuito che consente di modellare la crescita degli investimenti tenendo conto di contributi regolari, inflazione, tasse e vari tassi di rendimento.",
    h3: "3. Limitazione di responsabilità",
    p4_strong: "Il Servizio è a solo scopo informativo ed educativo.",
    l3_1: "I risultati dei calcoli sono approssimativi e illustrativi.",
    l3_2: "Il Servizio non fornisce consulenza finanziaria, di investimento, fiscale o legale.",
    l3_3: "Lo Sviluppatore non è responsabile per alcuna decisione finanziaria presa in base ai risultati del calcolatore.",
    l3_4: "Le cifre reali possono differire a causa di variazioni dei tassi di interesse, livelli di inflazione, leggi fiscali, commissioni e altri fattori di mercato.",
    l3_5: "I risultati passati non garantiscono quelli futuri.",
    p5: "Prima di prendere decisioni di investimento, raccomandiamo di consultare un consulente finanziario qualificato.",
    h4: "4. Proprietà intellettuale",
    p6: "Tutti i contenuti del Servizio, tra cui design, codice, testi, grafica e loghi, sono proprietà intellettuale dello Sviluppatore o vengono utilizzati in base a licenze appropriate. È vietato copiare, modificare o distribuire elementi del Servizio senza il previo consenso scritto dello Sviluppatore.",
    h5: "5. Disponibilità del Servizio",
    p7: "Lo Sviluppatore si impegna a garantire un funzionamento ininterrotto del Servizio, ma non ne garantisce la disponibilità continua. Il Servizio potrebbe non essere temporaneamente disponibile a causa di manutenzione, aggiornamenti o cause di forza maggiore.",
    h6: "6. Uso vietato",
    p8: "All'Utente è vietato:",
    l6_1: "utilizzare il Servizio per scopi illegali;",
    l6_2: "tentare di ottenere accesso non autorizzato al Servizio o alla sua infrastruttura;",
    l6_3: "utilizzare mezzi automatizzati (bot, scraper) per l'accesso di massa al Servizio;",
    l6_4: "spacciare i risultati del Servizio per consulenza finanziaria professionale.",
    h7: "7. Modifiche ai Termini",
    p9: "Lo Sviluppatore si riserva il diritto di modificare i presenti Termini. L'uso continuato del Servizio dopo le modifiche implica l'accettazione dei Termini aggiornati.",
    h8: "8. Legge applicabile",
    p10: "I presenti Termini sono disciplinati dall'attuale legislazione dell'Ucraina. Eventuali controversie che dovessero insorgere in relazione all'utilizzo del Servizio saranno risolte tramite negoziazioni e, se non si raggiunge un accordo, presso il tribunale competente della sede dello Sviluppatore.",
    h9: "9. Contatti",
    p11: "Per domande riguardanti i presenti Termini, contatta pokhyton.i@gmail.com."
  },
  pt: {
    title: "Termos de Uso",
    updated: "Última atualização: Junho de 2026",
    h1: "1. Assunto",
    p1: "Estes Termos de Uso (doravante - Termos) regem o relacionamento entre você (doravante - Usuário) e Redempsly (doravante - Desenvolvedor) a respeito do uso da aplicação web \"Juros Compostos\" (doravante - Serviço).",
    p2: "Ao usar o Serviço, você confirma que leu estes Termos e concorda com eles.",
    h2: "2. Descrição do Serviço",
    p3: "O Serviço é uma calculadora de juros compostos online gratuita que permite modelar o crescimento de investimentos levando em conta contribuições regulares, inflação, impostos e várias taxas de retorno.",
    h3: "3. Limitação de Responsabilidade",
    p4_strong: "O Serviço tem fins apenas informativos e educacionais.",
    l3_1: "Os resultados do cálculo são aproximados e ilustrativos.",
    l3_2: "O Serviço não é aconselhamento financeiro, de investimento, fiscal ou jurídico.",
    l3_3: "O Desenvolvedor não é responsável por quaisquer decisões financeiras tomadas com base nos resultados da calculadora.",
    l3_4: "Os números reais podem diferir devido a mudanças nas taxas de juros, níveis de inflação, leis fiscais, taxas e outros fatores de mercado.",
    l3_5: "O desempenho passado não garante resultados futuros.",
    p5: "Antes de tomar decisões de investimento, recomendamos consultar um consultor financeiro qualificado.",
    h4: "4. Propriedade Intelectual",
    p6: "Todo o conteúdo do Serviço, incluindo design, código, textos, gráficos e logotipos, é propriedade intelectual do Desenvolvedor ou é usado sob licenças apropriadas. É proibido copiar, modificar ou distribuir quaisquer elementos do Serviço sem o consentimento prévio por escrito do Desenvolvedor.",
    h5: "5. Disponibilidade do Serviço",
    p7: "O Desenvolvedor envida esforços para garantir o funcionamento ininterrupto do Serviço, mas não garante sua disponibilidade contínua. O Serviço pode estar temporariamente indisponível devido a manutenção, atualizações ou circunstâncias de força maior.",
    h6: "6. Uso Proibido",
    p8: "O Usuário está proibido de:",
    l6_1: "usar o Serviço para fins ilegais;",
    l6_2: "tentar obter acesso não autorizado ao Serviço ou à sua infraestrutura;",
    l6_3: "usar meios automatizados (bots, scrapers) para acesso em massa ao Serviço;",
    l6_4: "fazer passar os resultados do Serviço como aconselhamento financeiro profissional.",
    h7: "7. Alterações aos Termos",
    p9: "O Desenvolvedor reserva-se o direito de alterar estes Termos. O uso contínuo do Serviço após a realização de alterações significa o seu acordo com os Termos atualizados.",
    h8: "8. Lei Aplicável",
    p10: "Estes Termos são regidos pela atual legislação da Ucrânia. Quaisquer disputas que surjam relacionadas ao uso do Serviço devem ser resolvidas por meio de negociações e, se não for alcançado um acordo, no tribunal competente no local do Desenvolvedor.",
    h9: "9. Contatos",
    p11: "Para dúvidas em relação a estes Termos, contate pokhyton.i@gmail.com."
  },
  tr: {
    title: "Kullanım Koşulları",
    updated: "Son güncelleme: Haziran 2026",
    h1: "1. Konu",
    p1: "Bu Kullanım Koşulları (bundan böyle - Koşullar), \"Bileşik Faiz\" web uygulamasının (bundan böyle - Hizmet) kullanımına ilişkin sizinle (bundan böyle - Kullanıcı) Redempsly (bundan böyle - Geliştirici) arasındaki ilişkiyi yönetir.",
    p2: "Hizmeti kullanarak, bu Koşulları okuduğunuzu ve kabul ettiğinizi onaylarsınız.",
    h2: "2. Hizmet Açıklaması",
    p3: "Hizmet, düzenli katkıları, enflasyonu, vergileri ve çeşitli getiri oranlarını hesaba katarak yatırım büyümesini modellemeye olanak tanıyan ücretsiz bir çevrimiçi bileşik faiz hesap makinesidir.",
    h3: "3. Sorumluluğun Sınırlandırılması",
    p4_strong: "Hizmet yalnızca bilgilendirme ve eğitim amaçlıdır.",
    l3_1: "Hesaplama sonuçları yaklaşık değerlerdir ve açıklayıcı niteliktedir.",
    l3_2: "Hizmet, finans, yatırım, vergi veya yasal danışmanlık değildir.",
    l3_3: "Geliştirici, hesap makinesinin sonuçlarına göre alınan finansal kararlardan sorumlu değildir.",
    l3_4: "Gerçek rakamlar faiz oranları, enflasyon seviyeleri, vergi yasaları, ücretler ve diğer piyasa faktörlerindeki değişiklikler nedeniyle farklılık gösterebilir.",
    l3_5: "Geçmiş performans gelecekteki sonuçları garanti etmez.",
    p5: "Yatırım kararları almadan önce, nitelikli bir mali danışmana danışmanızı öneririz.",
    h4: "4. Fikri Mülkiyet",
    p6: "Tasarım, kod, metinler, grafikler ve logolar dahil olmak üzere Hizmetin tüm içeriği Geliştiricinin fikri mülkiyetidir veya uygun lisanslar altında kullanılır. Geliştiricinin önceden yazılı izni olmaksızen Hizmetin herhangi bir unsurunun kopyalanması, değiştirilmesi veya dağıtılması yasaktır.",
    h5: "5. Hizmetin Kullanılabilirliği",
    p7: "Geliştirici, Hizmetin kesintisiz çalışmasını sağlamak için çaba gösterir, ancak sürekli kullanılabilirliğini garanti etmez. Hizmet, bakım, güncellemeler veya mücbir sebeplerden dolayı geçici olarak kullanılamayabilir.",
    h6: "6. Yasaklanmış Kullanım",
    p8: "Kullanıcının aşağıdakileri yapması yasaktır:",
    l6_1: "Hizmeti yasadışı amaçlar için kullanmak;",
    l6_2: "Hizmete veya altyapısına yetkisiz erişim sağlamaya çalışmak;",
    l6_3: "Hizmete toplu erişim için otomatik araçlar (botlar, kazıyıcılar) kullanmak;",
    l6_4: "Hizmetin sonuçlarını profesyonel finansal tavsiye gibi göstermek.",
    h7: "7. Koşullardaki Değişiklikler",
    p9: "Geliştirici, bu Koşulları değiştirme hakkını saklı tutar. Değişiklikler yapıldıktan sonra Hizmetin kullanılmaya devam edilmesi, güncellenmiş Koşulları kabul ettiğiniz anlamına gelir.",
    h8: "8. Geçerli Yasa",
    p10: "Bu Koşullar Ukrayna'nın mevcut mevzuatına tabidir. Hizmetin kullanımıyla bağlantılı olarak ortaya çıkan her türlü anlaşmazlık, müzakereler yoluyla ve anlaşmaya varılamaması halinde Geliştiricinin bulunduğu yerdeki ilgili mahkemede çözülecektir.",
    h9: "9. İletişim",
    p11: "Bu Koşullarla ilgili sorularınız için pokhyton.i@gmail.com ile iletişime geçin."
  },
  zh: {
    title: "使用条款",
    updated: "最后更新：2026年6月",
    h1: "1. 标的",
    p1: "这些使用条款（以下简称 - 条款）管辖您（以下简称 - 用户）与Redempsly（以下简称 - 开发者）之间关于使用“复利”Web应用程序（以下简称 - 服务）的关系。",
    p2: "使用服务即表示您确认已阅读并同意这些条款。",
    h2: "2. 服务描述",
    p3: "该服务是一个免费的在线复利计算器，允许考虑定期供款、通货膨胀、税收和各种收益率来模拟投资增长。",
    h3: "3. 责任限制",
    p4_strong: "服务仅供参考和教育目的。",
    l3_1: "计算结果是近似值和说明性的。",
    l3_2: "服务不属于金融、投资、税务或法律建议。",
    l3_3: "开发者对基于计算器结果做出的任何财务决定概不负责。",
    l3_4: "实际数字可能会因利率、通货膨胀水平、税法、费用和其他市场因素的变化而有所不同。",
    l3_5: "过去的表现并不能保证未来的结果。",
    p5: "在做出投资决定之前，我们建议咨询合格的财务顾问。",
    h4: "4. 知识产权",
    p6: "服务的所有内容，包括设计、代码、文本、图形和徽标，均是开发者的知识产权或在适当的许可下使用。未经开发者事先书面同意，禁止复制、修改或分发服务的任何元素。",
    h5: "5. 服务可用性",
    p7: "开发者努力确保服务不间断运行，但不保证其持续可用性。由于维护、更新或不可抗力情况，服务可能会暂时无法使用。",
    h6: "6. 禁止的使用",
    p8: "禁止用户：",
    l6_1: "将服务用于非法目的；",
    l6_2: "试图未经授权访问服务或其基础架构；",
    l6_3: "使用自动化工具（机器人，抓取工具）对服务进行大规模访问；",
    l6_4: "将服务结果冒充专业财务建议。",
    h7: "7. 条款的变更",
    p9: "开发者保留更改这些条款的权利。在进行更改后继续使用服务即表示您同意更新的条款。",
    h8: "8. 适用法律",
    p10: "这些条款受乌克兰现行立法的管辖。与服务的使用相关的任何争议应通过协商解决，如果未能达成一致，则应在开发者所在地的相应法院解决。",
    h9: "9. 联系方式",
    p11: "有关这些条款的问题，请联系pokhyton.i@gmail.com。"
  },
  ja: {
    title: "利用規約",
    updated: "最終更新日：2026年6月",
    h1: "1. 主題",
    p1: "これらの利用規約（以下、規約）は、「複利」Webアプリケーション（以下、サービス）の使用に関するお客様（以下、ユーザー）とRedempsly（以下、開発者）の間の関係を規定するものです。",
    p2: "サービスを使用することにより、お客様はこれらの規約を読み、これに同意したことを確認するものとします。",
    h2: "2. サービスの説明",
    p3: "本サービスは、定期的な拠出、インフレ、税金、およびさまざまな収益率を考慮して、投資の成長をモデル化できる無料のオンライン複利計算機です。",
    h3: "3. 責任の制限",
    p4_strong: "サービスは、情報提供および教育目的でのみ提供されます。",
    l3_1: "計算結果は近似値であり、説明のためのものです。",
    l3_2: "サービスは、財務、投資、税務、または法律上のアドバイスではありません。",
    l3_3: "開発者は、計算機の結果に基づいて行われたいかなる財務上の決定についても責任を負いません。",
    l3_4: "実際の数値は、金利、インフレ率、税法、手数料、およびその他の市場要因の変化により異なる場合があります。",
    l3_5: "過去のパフォーマンスは将来の結果を保証するものではありません。",
    p5: "投資決定を行う前に、資格のある財務アドバイザーに相談することをお勧めします。",
    h4: "4. 知的財産",
    p6: "デザイン、コード、テキスト、グラフィック、ロゴなど、サービスのすべてのコンテンツは、開発者の知的財産であるか、適切なライセンスの下で使用されています。開発者の事前の書面による同意なしに、サービスのいかなる要素もコピー、変更、または配布することは禁じられています。",
    h5: "5. サービスの可用性",
    p7: "開発者は、サービスの中断のない運用を確実にするよう努めますが、継続的な可用性を保証するものではありません。メンテナンス、アップデート、または不可抗力の状況により、サービスが一時的に利用できなくなる場合があります。",
    h6: "6. 禁止されている使用",
    p8: "ユーザーは以下のことを禁じられています:",
    l6_1: "違法な目的でサービスを使用すること;",
    l6_2: "サービスまたはそのインフラストラクチャへの不正アクセスを試みること;",
    l6_3: "サービスへの大量アクセスのために自動化された手段（ボット、スクレイパー）を使用すること;",
    l6_4: "サービスの結果を専門的な財務アドバイスとして偽ること。",
    h7: "7. 規約の変更",
    p9: "開発者は、これらの規約を変更する権利を留保します。変更が加えられた後もサービスを継続して使用することにより、更新された規約に同意したものとみなされます。",
    h8: "8. 準拠法",
    p10: "これらの規約は、ウクライナの現行の法律に準拠します。サービスの使用に関連して生じた紛争は交渉を通じて解決され、合意に達しない場合は、開発者の所在地の管轄裁判所で解決されるものとします。",
    h9: "9. 連絡先",
    p11: "これらの規約に関する質問については、pokhyton.i@gmail.comまでご連絡ください。"
  },
  ko: {
    title: "이용 약관",
    updated: "최근 업데이트: 2026년 6월",
    h1: "1. 목적",
    p1: "본 이용 약관(이하 약관)은 \"복리\" 웹 애플리케이션(이하 서비스)의 사용과 관련하여 귀하(이하 사용자)와 Redempsly(이하 개발자) 간의 관계를 규율합니다.",
    p2: "서비스를 이용함으로써 귀하는 본 약관을 읽고 동의함을 확인합니다.",
    h2: "2. 서비스 설명",
    p3: "이 서비스는 정기적인 납입, 인플레이션, 세금 및 다양한 수익률을 고려하여 투자 성장을 모델링할 수 있는 무료 온라인 복리 계산기입니다.",
    h3: "3. 책임의 한계",
    p4_strong: "서비스는 정보 및 교육 목적으로만 제공됩니다.",
    l3_1: "계산 결과는 근사치이며 설명을 위한 것입니다.",
    l3_2: "이 서비스는 재정, 투자, 세무 또는 법률 자문이 아닙니다.",
    l3_3: "개발자는 계산기의 결과를 바탕으로 내린 재정적 결정에 대해 책임을 지지 않습니다.",
    l3_4: "실제 수치는 금리, 인플레이션 수준, 세법, 수수료 및 기타 시장 요인의 변화로 인해 다를 수 있습니다.",
    l3_5: "과거 실적이 미래 결과를 보장하지 않습니다.",
    p5: "투자 결정을 내리기 전에 자격을 갖춘 재무 고문과 상담하는 것이 좋습니다.",
    h4: "4. 지적 재산",
    p6: "디자인, 코드, 텍스트, 그래픽 및 로고를 포함한 서비스의 모든 콘텐츠는 개발자의 지적 재산이거나 적절한 라이선스에 따라 사용됩니다. 개발자의 사전 서면 동의 없이 서비스의 요소를 복사, 수정 또는 배포하는 것은 금지됩니다.",
    h5: "5. 서비스 가용성",
    p7: "개발자는 서비스의 중단 없는 운영을 보장하기 위해 노력하지만 지속적인 가용성을 보장하지는 않습니다. 유지 관리, 업데이트 또는 불가항력 상황으로 인해 서비스가 일시적으로 중단될 수 있습니다.",
    h6: "6. 금지된 사용",
    p8: "사용자는 다음 행위가 금지됩니다:",
    l6_1: "불법적인 목적으로 서비스를 사용하는 행위;",
    l6_2: "서비스 또는 그 인프라에 무단으로 접근을 시도하는 행위;",
    l6_3: "서비스에 대량으로 액세스하기 위해 자동화된 수단(봇, 스크레이퍼)을 사용하는 행위;",
    l6_4: "서비스의 결과를 전문적인 재정적 조언으로 가장하는 행위.",
    h7: "7. 약관의 변경",
    p9: "개발자는 본 약관을 변경할 권리를 보유합니다. 변경된 후에도 서비스를 계속 사용하면 업데이트된 약관에 동의하는 것으로 간주됩니다.",
    h8: "8. 준거법",
    p10: "본 약관은 우크라이나의 현행법에 따릅니다. 서비스 사용과 관련하여 발생하는 모든 분쟁은 협상을 통해 해결되며, 합의에 도달하지 못한 경우 개발자 소재지의 관할 법원에서 해결합니다.",
    h9: "9. 연락처",
    p11: "본 약관에 관한 질문은 pokhyton.i@gmail.com으로 문의하십시오."
  },
  hi: {
    title: "उपयोग की शर्तें",
    updated: "अंतिम अद्यतन: जून 2026",
    h1: "1. विषय वस्तु",
    p1: "ये उपयोग की शर्तें (इसके बाद - शर्तें) \"चक्रवृद्धि ब्याज\" वेब एप्लिकेशन (इसके बाद - सेवा) के उपयोग के संबंध में आपके (इसके बाद - उपयोगकर्ता) और Redempsly (इसके बाद - डेवलपर) के बीच संबंधों को नियंत्रित करती हैं।",
    p2: "सेवा का उपयोग करके, आप पुष्टि करते हैं कि आपने इन शर्तों को पढ़ लिया है और उनसे सहमत हैं।",
    h2: "2. सेवा विवरण",
    p3: "सेवा एक निःशुल्क ऑनलाइन चक्रवृद्धि ब्याज कैलकुलेटर है जो नियमित योगदान, मुद्रास्फीति, करों और वापसी की विभिन्न दरों को ध्यान में रखते हुए निवेश वृद्धि मॉडलिंग की अनुमति देता है।",
    h3: "3. दायित्व की सीमा",
    p4_strong: "सेवा केवल सूचनात्मक और शैक्षिक उद्देश्यों के लिए है।",
    l3_1: "गणना के परिणाम अनुमानित और उदाहरणात्मक हैं।",
    l3_2: "सेवा वित्तीय, निवेश, कर या कानूनी सलाह नहीं है।",
    l3_3: "डेवलपर कैलकुलेटर के परिणामों के आधार पर लिए गए किसी भी वित्तीय निर्णय के लिए जिम्मेदार नहीं है।",
    l3_4: "ब्याज दरों, मुद्रास्फीति के स्तर, कर कानूनों, शुल्क और अन्य बाजार कारकों में बदलाव के कारण वास्तविक आंकड़े भिन्न हो सकते हैं।",
    l3_5: "पिछला प्रदर्शन भविष्य के परिणामों की गारंटी नहीं देता है।",
    p5: "निवेश संबंधी निर्णय लेने से पहले, हम किसी योग्य वित्तीय सलाहकार से परामर्श करने की सलाह देते हैं।",
    h4: "4. बौद्धिक संपदा",
    p6: "डिज़ाइन, कोड, टेक्स्ट, ग्राफ़िक्स और लोगो सहित सेवा की सभी सामग्री, डेवलपर की बौद्धिक संपदा है या उपयुक्त लाइसेंस के तहत उपयोग की जाती है। डेवलपर की पूर्व लिखित सहमति के बिना सेवा के किसी भी तत्व की प्रतिलिपि बनाना, संशोधित करना या वितरित करना निषिद्ध है।",
    h5: "5. सेवा की उपलब्धता",
    p7: "डेवलपर सेवा के निर्बाध संचालन को सुनिश्चित करने के लिए प्रयास करता है, लेकिन इसकी निरंतर उपलब्धता की गारंटी नहीं देता है। सेवा रखरखाव, अद्यतन या अप्रत्याशित परिस्थितियों के कारण अस्थायी रूप से अनुपलब्ध हो सकती है।",
    h6: "6. निषिद्ध उपयोग",
    p8: "उपयोगकर्ता को निषिद्ध किया गया है:",
    l6_1: "अवैध उद्देश्यों के लिए सेवा का उपयोग करना;",
    l6_2: "सेवा या उसके बुनियादी ढांचे तक अनधिकृत पहुंच प्राप्त करने का प्रयास करना;",
    l6_3: "सेवा तक बड़े पैमाने पर पहुंच के लिए स्वचालित साधनों (बॉट, स्क्रैपर) का उपयोग करना;",
    l6_4: "सेवा के परिणामों को पेशेवर वित्तीय सलाह के रूप में प्रस्तुत करना।",
    h7: "7. शर्तों में परिवर्तन",
    p9: "डेवलपर के पास इन शर्तों को बदलने का अधिकार सुरक्षित है। परिवर्तन किए जाने के बाद सेवा का निरंतर उपयोग अद्यतन शर्तों के साथ आपके समझौते को दर्शाता है।",
    h8: "8. लागू कानून",
    p10: "ये शर्तें यूक्रेन के वर्तमान कानून द्वारा शासित हैं। सेवा के उपयोग के संबंध में उत्पन्न होने वाले किसी भी विवाद को बातचीत के माध्यम से हल किया जाएगा, और यदि समझौता नहीं होता है, तो डेवलपर के स्थान पर उपयुक्त अदालत में।",
    h9: "9. संपर्क",
    p11: "इन शर्तों के संबंध में प्रश्नों के लिए, pokhyton.i@gmail.com पर संपर्क करें।"
  },
  ar: {
    title: "شروط الاستخدام",
    updated: "آخر تحديث: يونيو 2026",
    h1: "1. موضوع",
    p1: "تحكم شروط الاستخدام هذه (المشار إليها فيما يلي - الشروط) العلاقة بينك (المشار إليه فيما يلي - المستخدم) و Redempsly (المشار إليه فيما يلي - المطور) فيما يتعلق باستخدام تطبيق الويب \"الفائدة المركبة\" (المشار إليه فيما يلي - الخدمة).",
    p2: "باستخدام الخدمة، فإنك تؤكد أنك قرأت هذه الشروط وتوافق عليها.",
    h2: "2. وصف الخدمة",
    p3: "الخدمة عبارة عن آلة حاسبة مجانية للفائدة المركبة عبر الإنترنت تسمح بنمذجة نمو الاستثمار مع مراعاة المساهمات المنتظمة والتضخم والضرائب ومعدلات العائد المختلفة.",
    h3: "3. تحديد المسؤولية",
    p4_strong: "الخدمة للأغراض الإعلامية والتعليمية فقط.",
    l3_1: "نتائج الحساب تقريبية وتوضيحية.",
    l3_2: "الخدمة ليست نصيحة مالية أو استثمارية أو ضريبية أو قانونية.",
    l3_3: "المطور غير مسؤول عن أي قرارات مالية يتم اتخاذها بناءً على نتائج الآلة الحاسبة.",
    l3_4: "قد تختلف الأرقام الحقيقية بسبب التغيرات في أسعار الفائدة ومستويات التضخم وقوانين الضرائب والرسوم وعوامل السوق الأخرى.",
    l3_5: "الأداء السابق لا يضمن النتائج المستقبلية.",
    p5: "قبل اتخاذ قرارات الاستثمار، نوصي باستشارة مستشار مالي مؤهل.",
    h4: "4. الملكية الفكرية",
    p6: "جميع محتويات الخدمة، بما في ذلك التصميم والرمز والنصوص والرسومات والشعارات، هي ملكية فكرية للمطور أو تُستخدم بموجب تراخيص مناسبة. يُحظر نسخ أو تعديل أو توزيع أي عناصر من الخدمة دون موافقة كتابية مسبقة من المطور.",
    h5: "5. توفر الخدمة",
    p7: "يبذل المطور جهودًا لضمان التشغيل المتواصل للخدمة، لكنه لا يضمن توفرها المستمر. قد تكون الخدمة غير متوفرة مؤقتًا بسبب الصيانة أو التحديثات أو ظروف القوة القاهرة.",
    h6: "6. الاستخدام المحظور",
    p8: "يحظر على المستخدم:",
    l6_1: "استخدام الخدمة لأغراض غير قانونية؛",
    l6_2: "محاولة الوصول غير المصرح به إلى الخدمة أو البنية التحتية الخاصة بها؛",
    l6_3: "استخدام وسائل آلية (روبوتات، كاشطات) للوصول الشامل إلى الخدمة؛",
    l6_4: "تمرير نتائج الخدمة كنصيحة مالية مهنية.",
    h7: "7. التغييرات في الشروط",
    p9: "يحتفظ المطور بالحق في تغيير هذه الشروط. الاستخدام المستمر للخدمة بعد إجراء التغييرات يعني موافقتك على الشروط المحدثة.",
    h8: "8. القانون المعمول به",
    p10: "تخضع هذه الشروط للتشريعات الحالية في أوكرانيا. يجب حل أي نزاعات تنشأ فيما يتعلق باستخدام الخدمة من خلال المفاوضات، وفي حالة عدم التوصل إلى اتفاق، في المحكمة المناسبة في موقع المطور.",
    h9: "9. جهات الاتصال",
    p11: "للأسئلة المتعلقة بهذه الشروط، اتصل بـ pokhyton.i@gmail.com."
  }
};

export const TermsOfUse = ({}: Props) => {
  const { locale: lang } = useTranslation();

  const t = (content as any)[lang] || content.en;
  
  return (
    <LegalPageLayout>
      <div dir={lang === 'ar' ? 'rtl' : 'ltr'}>
        <h1>{t.title}</h1>
        <p className="last-updated">{t.updated}</p>

        <h2>{t.h1}</h2>
        <p>{t.p1}</p>
        <p>{t.p2}</p>

        <h2>{t.h2}</h2>
        <p>{t.p3}</p>

        <h2>{t.h3}</h2>
        <p><strong>{t.p4_strong}</strong></p>
        <ul>
          <li>{t.l3_1}</li>
          <li>{t.l3_2}</li>
          <li>{t.l3_3}</li>
          <li>{t.l3_4}</li>
          <li>{t.l3_5}</li>
        </ul>
        <p>{t.p5}</p>

        <h2>{t.h4}</h2>
        <p>{t.p6}</p>

        <h2>{t.h5}</h2>
        <p>{t.p7}</p>

        <h2>{t.h6}</h2>
        <p>{t.p8}</p>
        <ul>
          <li>{t.l6_1}</li>
          <li>{t.l6_2}</li>
          <li>{t.l6_3}</li>
          <li>{t.l6_4}</li>
        </ul>

        <h2>{t.h7}</h2>
        <p>{t.p9}</p>

        <h2>{t.h8}</h2>
        <p>{t.p10}</p>

        <h2>{t.h9}</h2>
        <p>{t.p11}</p>
      </div>
    </LegalPageLayout>
  );
};
